/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

 /*
 * Inicial.java
 *
 * Created on 18-nov-2011, 12:51:01
 */
package prueba1;

import clase.Imagen;
import clase.RoundedBorder;
import clase.TextPrompt;
import java.awt.Graphics;
import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JPanel;

/**
 *
 * @author Pedro
 */
public class preInicio extends javax.swing.JPanel {

    /**
     * Creates new form Inicial
     */
    private ventana v;
    private Integer indiceFoto = 0;

    public ventana getV() {
        return v;
    }

    public void setV(ventana v) {
        this.v = v;
    }

    public preInicio() {
        initComponents();
        this.selecEsp.setOpaque(false);
                this.selecEsp1.setOpaque(false);
        selecEsp2.setOpaque(false);
        selecEsp.setOpaque(true);
        
    }

    public void cargarImagenes() {

        Imagen a = new Imagen(fondo, "/Images/fondo.png");
        fondo.add(a).repaint();
        a = new Imagen(comenzar, "/Images/comenzar.png");
        comenzar.add(a).repaint();
        a = new Imagen(logo, "/Images/logo.png");
        logo.add(a).repaint();
        a= new Imagen (bandera, "/Images/espana.png");
        bandera.add(a).repaint();
        a= new Imagen (bandera1, "/Images/francia.png");
        bandera1.add(a).repaint();
         a= new Imagen (bandera2, "/Images/ingles.png");
        bandera2.add(a).repaint();

    }

    private void setFotoEscalada(JLabel lblFoto, String rutafoto) {
        ImageIcon foto = new ImageIcon(getClass().getResource(rutafoto));
        Icon icono = new ImageIcon(foto.getImage().getScaledInstance(lblFoto.getWidth(), lblFoto.getHeight(), 1));
        lblFoto.setIcon(icono);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fondo = new javax.swing.JPanel();
        comenzar = new javax.swing.JPanel();
        titulo = new javax.swing.JLabel();
        logo = new javax.swing.JPanel();
        idioma = new javax.swing.JLabel();
        banderaF = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        banderaI = new javax.swing.JPanel();
        selecEsp = new javax.swing.JPanel();
        espanol = new javax.swing.JLabel();
        bandera = new javax.swing.JPanel();
        selecEsp1 = new javax.swing.JPanel();
        frances = new javax.swing.JLabel();
        bandera1 = new javax.swing.JPanel();
        selecEsp2 = new javax.swing.JPanel();
        ingles = new javax.swing.JLabel();
        bandera2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();

        fondo.setBackground(new java.awt.Color(0, 0, 0));

        comenzar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        comenzar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                comenzarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout comenzarLayout = new javax.swing.GroupLayout(comenzar);
        comenzar.setLayout(comenzarLayout);
        comenzarLayout.setHorizontalGroup(
            comenzarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 227, Short.MAX_VALUE)
        );
        comenzarLayout.setVerticalGroup(
            comenzarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 183, Short.MAX_VALUE)
        );

        titulo.setText("<html> <h1 style=\"color: #FAFAFA;  font-size: 40pt\"> BIENVENIDO A SEAL</h1> </html>");

        javax.swing.GroupLayout logoLayout = new javax.swing.GroupLayout(logo);
        logo.setLayout(logoLayout);
        logoLayout.setHorizontalGroup(
            logoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 122, Short.MAX_VALUE)
        );
        logoLayout.setVerticalGroup(
            logoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 74, Short.MAX_VALUE)
        );

        idioma.setText("<html> <h2 style=\"color: #FAFAFA; font-size: 21pt\"> Selecciona un dioma</h1> </html>");

        javax.swing.GroupLayout banderaFLayout = new javax.swing.GroupLayout(banderaF);
        banderaF.setLayout(banderaFLayout);
        banderaFLayout.setHorizontalGroup(
            banderaFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        banderaFLayout.setVerticalGroup(
            banderaFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 54, Short.MAX_VALUE)
        );

        jLabel5.setText(" ");

        javax.swing.GroupLayout banderaILayout = new javax.swing.GroupLayout(banderaI);
        banderaI.setLayout(banderaILayout);
        banderaILayout.setHorizontalGroup(
            banderaILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        banderaILayout.setVerticalGroup(
            banderaILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 54, Short.MAX_VALUE)
        );

        selecEsp.setBackground(new java.awt.Color(232, 232, 232));
        selecEsp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                selecEspMouseClicked(evt);
            }
        });

        espanol.setText("<html> <h2 style=\"color: #00000; font-size: 25pt\"> Español</h1> </html>");

        javax.swing.GroupLayout banderaLayout = new javax.swing.GroupLayout(bandera);
        bandera.setLayout(banderaLayout);
        banderaLayout.setHorizontalGroup(
            banderaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 75, Short.MAX_VALUE)
        );
        banderaLayout.setVerticalGroup(
            banderaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 54, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout selecEspLayout = new javax.swing.GroupLayout(selecEsp);
        selecEsp.setLayout(selecEspLayout);
        selecEspLayout.setHorizontalGroup(
            selecEspLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(selecEspLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bandera, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(espanol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
        );
        selecEspLayout.setVerticalGroup(
            selecEspLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(selecEspLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(selecEspLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(espanol)
                    .addComponent(bandera, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        selecEsp1.setBackground(new java.awt.Color(232, 232, 232));
        selecEsp1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        selecEsp1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                selecEsp1MouseClicked(evt);
            }
        });

        frances.setText("<html> <h2 style=\"color: #FAFAFA; font-size: 25pt\"> Francés</h1> </html>");

        bandera1.setPreferredSize(new java.awt.Dimension(102, 54));

        javax.swing.GroupLayout bandera1Layout = new javax.swing.GroupLayout(bandera1);
        bandera1.setLayout(bandera1Layout);
        bandera1Layout.setHorizontalGroup(
            bandera1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 72, Short.MAX_VALUE)
        );
        bandera1Layout.setVerticalGroup(
            bandera1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 54, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout selecEsp1Layout = new javax.swing.GroupLayout(selecEsp1);
        selecEsp1.setLayout(selecEsp1Layout);
        selecEsp1Layout.setHorizontalGroup(
            selecEsp1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(selecEsp1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bandera1, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(frances, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );
        selecEsp1Layout.setVerticalGroup(
            selecEsp1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(selecEsp1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(selecEsp1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(frances)
                    .addComponent(bandera1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        selecEsp2.setBackground(new java.awt.Color(232, 232, 232));
        selecEsp2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        selecEsp2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                selecEsp2MouseClicked(evt);
            }
        });

        ingles.setText("<html> <h2 style=\"color: #FAFAFA; font-size: 25pt\"> Ingés</h1> </html>");

        javax.swing.GroupLayout bandera2Layout = new javax.swing.GroupLayout(bandera2);
        bandera2.setLayout(bandera2Layout);
        bandera2Layout.setHorizontalGroup(
            bandera2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 73, Short.MAX_VALUE)
        );
        bandera2Layout.setVerticalGroup(
            bandera2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 54, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout selecEsp2Layout = new javax.swing.GroupLayout(selecEsp2);
        selecEsp2.setLayout(selecEsp2Layout);
        selecEsp2Layout.setHorizontalGroup(
            selecEsp2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(selecEsp2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bandera2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(ingles, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(56, Short.MAX_VALUE))
        );
        selecEsp2Layout.setVerticalGroup(
            selecEsp2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(selecEsp2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(selecEsp2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ingles)
                    .addComponent(bandera2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jLabel3.setText("<html> <h2 style=\"color: #FAFAFA; font-size: 30pt\"> GO!</h1> </html>");

        javax.swing.GroupLayout fondoLayout = new javax.swing.GroupLayout(fondo);
        fondo.setLayout(fondoLayout);
        fondoLayout.setHorizontalGroup(
            fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fondoLayout.createSequentialGroup()
                .addGroup(fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(fondoLayout.createSequentialGroup()
                        .addGap(158, 158, 158)
                        .addGroup(fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(fondoLayout.createSequentialGroup()
                                .addGroup(fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(banderaF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(banderaI, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(fondoLayout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(selecEsp1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(selecEsp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(selecEsp2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(fondoLayout.createSequentialGroup()
                                        .addGap(83, 83, 83)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(comenzar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(fondoLayout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addComponent(idioma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(fondoLayout.createSequentialGroup()
                        .addGap(209, 209, 209)
                        .addComponent(logo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fondoLayout.createSequentialGroup()
                .addGap(0, 82, Short.MAX_VALUE)
                .addComponent(titulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53))
            .addGroup(fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fondoLayout.createSequentialGroup()
                    .addContainerGap(281, Short.MAX_VALUE)
                    .addComponent(jLabel5)
                    .addGap(150, 150, 150)))
        );
        fondoLayout.setVerticalGroup(
            fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fondoLayout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(titulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(logo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(idioma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(selecEsp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(fondoLayout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(banderaF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(fondoLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(selecEsp1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(selecEsp2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 95, Short.MAX_VALUE)
                .addComponent(comenzar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(banderaI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(211, Short.MAX_VALUE))
            .addGroup(fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(fondoLayout.createSequentialGroup()
                    .addGap(306, 306, 306)
                    .addComponent(jLabel5)
                    .addContainerGap(683, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(fondo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void comenzarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_comenzarMouseClicked
        // TODO add your handling code here:

        Inicial pp = new Inicial();
        pp.setV(this.v);
        v.setContentPane(pp);
        v.setVisible(true);
        pp.setVisible(true);
        pp.cargarImagenes();

    }//GEN-LAST:event_comenzarMouseClicked

    private void selecEsp1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_selecEsp1MouseClicked
        // TODO add your handling code here:
        frances.setText("<html> <h2 style=\"color: #000000; font-size: 25pt\">Francés</h1> </html>");     
                espanol.setText("<html> <h2 style=\"color: #FAFAFA; font-size: 25pt\"> Español</h1> </html>");
                ingles.setText("<html> <h2 style=\"color: #FAFAFA; font-size: 25pt\"> Ingés</h1> </html>");
                this.selecEsp1.setOpaque(true);
                this.selecEsp.setOpaque(false);
                this.selecEsp2.setOpaque(false);
                this.titulo.setText("<html> <h1 style=\"color: #FAFAFA;  font-size: 40pt\">BIENVENUE À SEAL</h1> </html>");
                idioma.setText("<html> <h2 style=\"color: #FAFAFA; font-size: 21pt\"> Sélectionnez une langue</h1> </html>");
                selecEsp2.repaint();
          selecEsp.repaint();
          selecEsp1.repaint();
                
                
    }//GEN-LAST:event_selecEsp1MouseClicked

    private void selecEspMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_selecEspMouseClicked
        // TODO add your handling code here:
                  espanol.setText("<html> <h2 style=\"color: #00000; font-size: 25pt\"> Español</h1> </html>");
           frances.setText("<html> <h2 style=\"color: #FAFAFA; font-size: 25pt\">Francés</h1> </html>");
           ingles.setText("<html> <h2 style=\"color: #FAFAFA; font-size: 25pt\"> Ingés</h1> </html>");
            this.titulo.setText("<html> <h1 style=\"color: #FAFAFA;  font-size: 40pt\">BIENVENIDO A SEAL</h1> </html>");
          this.selecEsp1.setOpaque(false);
          this.selecEsp.setOpaque(true);
          this.selecEsp2.setOpaque(false);
          idioma.setText("<html> <h2 style=\"color: #FAFAFA; font-size: 21pt\"> Selecciona un dioma</h1> </html>");
          selecEsp2.repaint();
          selecEsp.repaint();
          selecEsp1.repaint();
    
    }//GEN-LAST:event_selecEspMouseClicked

    private void selecEsp2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_selecEsp2MouseClicked
        // TODO add your handling code here:
                        espanol.setText("<html> <h2 style=\"color: #FAFAFA; font-size: 25pt\"> Español</h1> </html>");
           frances.setText("<html> <h2 style=\"color: #FAFAFA; font-size: 25pt\">Francés</h1> </html>");
           ingles.setText("<html> <h2 style=\"color: #00000; font-size: 25pt\"> Ingés</h1> </html>");
            this.titulo.setText("<html> <h1 style=\"color: #FAFAFA;  font-size: 40pt\"> WELCOME TO SEAL</h1> </html>");
            idioma.setText("<html> <h2 style=\"color: #FAFAFA; font-size: 21pt\"> Select a language</h1> </html>");

          this.selecEsp1.setOpaque(false);
          this.selecEsp.setOpaque(false);
          this.selecEsp2.setOpaque(true);
          selecEsp2.repaint();
          selecEsp.repaint();
          selecEsp1.repaint();
    }//GEN-LAST:event_selecEsp2MouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bandera;
    private javax.swing.JPanel bandera1;
    private javax.swing.JPanel bandera2;
    private javax.swing.JPanel banderaF;
    private javax.swing.JPanel banderaI;
    private javax.swing.JPanel comenzar;
    private javax.swing.JLabel espanol;
    private javax.swing.JPanel fondo;
    private javax.swing.JLabel frances;
    private javax.swing.JLabel idioma;
    private javax.swing.JLabel ingles;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel logo;
    private javax.swing.JPanel selecEsp;
    private javax.swing.JPanel selecEsp1;
    private javax.swing.JPanel selecEsp2;
    private javax.swing.JLabel titulo;
    // End of variables declaration//GEN-END:variables
}
