/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package prueba1;

import clase.Dialogo;
import clase.Imagen;
import clase.Pago;
import clase.RoundedBorder;
import clase.TextPrompt;
import com.sun.org.apache.xpath.internal.operations.Bool;
import java.awt.Color;
import javax.swing.BoundedRangeModel;
import javax.swing.UIManager;
import javax.swing.event.ChangeEvent;
import javax.swing.event.ChangeListener;
import javax.swing.plaf.ColorUIResource;

/**
 *
 * @author nerea
 */
public class Reserva3 extends javax.swing.JPanel {

    private ventana v;
    private clase.Reserva a;
    private Pago pago;
    private boolean flag=false;
    /**
     * Creates new form Viajes
     */


    public Reserva3(clase.Reserva a, Pago pago) {
        initComponents();
        this.a = a;
        this.precioAdulto.setText(String.valueOf(a.getPrecio_adulto()));
        this.precioNinos.setText(String.valueOf(a.getPrecio_nino()));
        this.precioGrupo.setText(String.valueOf(a.getPrecio_grupo()));
        this.total.setText(String.valueOf(a.getTotal()));
        this.numeroAdultos.setValue(a.getNumero_entradas_adulto());
        this.numeroNinhos.setValue(a.getNumero_entradas_nino());
        this.destino.setSelectedItem(a.getDestino());
        this.fechas.setSelectedItem(a.getFecha());
        this.lugarSalida.setText(a.getLugar_salida());
        this.embarque.setText(a.getEmbarcadero());
        this.horaSalida.setText(a.getHora_salida());
        this.horaLlegada.setText(a.getHora_llegada());
        this.pago= pago;
        this.CVC.setText(pago.getCVC());
        this.nTarjeta.setText(pago.getNumero_tarjeta());
        this.nombre.setText(pago.getNombre_titular());
        this.fechaCaducidad.setText(pago.getFecha_caducidad());
        

      

    }

    public ventana getV() {
        return v;
    }

    public void setV(ventana v) {
        this.v = v;
    }

    public void cargarImagenes() {
        Imagen a = new Imagen(casa, "/Images/casa.png");
        casa.add(a).repaint();

        a = new Imagen(prog, "/Images/prog.png");
        prog.add(a).repaint();

        a = new Imagen(reserva, "/Images/reservaseleccion.png");
        reserva.add(a).repaint();
        a = new Imagen(ayuda, "/Images/ayuda.png");
        ayuda.add(a).repaint();
        a = new Imagen(cartera, "/Images/cartera.png");
        cartera.add(a).repaint();
        a = new Imagen(buscar, "/Images/buscar.png");
        buscar.add(a).repaint();

        a = new Imagen(logo, "/Images/logo.png");
        logo.add(a).repaint();
        a = new Imagen(grafica, "/Images/compra2.png");
        grafica.add(a).repaint();
        jScrollPane1.getVerticalScrollBar().getModel().addChangeListener((ChangeEvent e) -> {
            BoundedRangeModel m = (BoundedRangeModel) e.getSource();
            int extent = m.getExtent();
            int maximum = m.getMaximum();
            int value = m.getValue();
            if (value + extent >= maximum) {
                siguiente.setEnabled(true);
            }
        });
        if(flag){
             siguiente.setEnabled(true);
        }
        a= new Imagen (volver, "/Images/volver.png");
        volver.add(a).repaint();
        UIManager.put("Button.disabledText", new ColorUIResource(180, 180, 180));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        logo = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jbusqueda3 = new javax.swing.JTextField();
        buscar = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        cartera = new javax.swing.JPanel();
        casa = new javax.swing.JPanel();
        reserva = new javax.swing.JPanel();
        prog = new javax.swing.JPanel();
        ayuda = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        Cancelar = new javax.swing.JButton();
        grafica = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel9 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        fechas = new javax.swing.JComboBox<>();
        destino = new javax.swing.JComboBox<>();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        numeroNinhos = new javax.swing.JSpinner();
        numeroAdultos = new javax.swing.JSpinner();
        precioNinos = new javax.swing.JLabel();
        precioGrupo = new javax.swing.JLabel();
        precioAdulto = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        cont4 = new javax.swing.JPanel();
        lugarSalida = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        horaLlegada = new javax.swing.JTextField();
        embarque = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        horaSalida = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        total = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        CVC = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        fechaCaducidad = new javax.swing.JTextField();
        nombre = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        nTarjeta = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        btnPago = new javax.swing.JButton();
        btnEntradas = new javax.swing.JButton();
        btnEntradas1 = new javax.swing.JButton();
        text5 = new javax.swing.JLabel();
        text6 = new javax.swing.JLabel();
        text7 = new javax.swing.JLabel();
        text8 = new javax.swing.JLabel();
        siguiente = new javax.swing.JButton();
        anterior = new javax.swing.JButton();
        volver = new javax.swing.JPanel();

        setBackground(new java.awt.Color(250, 250, 250));
        setPreferredSize(new java.awt.Dimension(521, 946));

        javax.swing.GroupLayout logoLayout = new javax.swing.GroupLayout(logo);
        logo.setLayout(logoLayout);
        logoLayout.setHorizontalGroup(
            logoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 147, Short.MAX_VALUE)
        );
        logoLayout.setVerticalGroup(
            logoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 57, Short.MAX_VALUE)
        );

        jPanel6.setBackground(new java.awt.Color(146, 194, 197));

        jbusqueda3.setBackground(new java.awt.Color(146, 194, 197));
        jbusqueda3.setFont(new java.awt.Font("Segoe UI", 1, 21)); // NOI18N
        jbusqueda3.setForeground(new java.awt.Color(255, 255, 255));
        jbusqueda3.setBorder(null);
        jbusqueda3.setCaretColor(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout buscarLayout = new javax.swing.GroupLayout(buscar);
        buscar.setLayout(buscarLayout);
        buscarLayout.setHorizontalGroup(
            buscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );
        buscarLayout.setVerticalGroup(
            buscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addComponent(jbusqueda3, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(buscar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbusqueda3, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(146, 194, 197));

        cartera.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cartera.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                carteraMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout carteraLayout = new javax.swing.GroupLayout(cartera);
        cartera.setLayout(carteraLayout);
        carteraLayout.setHorizontalGroup(
            carteraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 68, Short.MAX_VALUE)
        );
        carteraLayout.setVerticalGroup(
            carteraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 65, Short.MAX_VALUE)
        );

        casa.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        casa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                casaMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout casaLayout = new javax.swing.GroupLayout(casa);
        casa.setLayout(casaLayout);
        casaLayout.setHorizontalGroup(
            casaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 68, Short.MAX_VALUE)
        );
        casaLayout.setVerticalGroup(
            casaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 65, Short.MAX_VALUE)
        );

        reserva.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        reserva.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                reservaMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout reservaLayout = new javax.swing.GroupLayout(reserva);
        reserva.setLayout(reservaLayout);
        reservaLayout.setHorizontalGroup(
            reservaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 68, Short.MAX_VALUE)
        );
        reservaLayout.setVerticalGroup(
            reservaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 65, Short.MAX_VALUE)
        );

        prog.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        prog.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                progMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout progLayout = new javax.swing.GroupLayout(prog);
        prog.setLayout(progLayout);
        progLayout.setHorizontalGroup(
            progLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 68, Short.MAX_VALUE)
        );
        progLayout.setVerticalGroup(
            progLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 65, Short.MAX_VALUE)
        );

        ayuda.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ayuda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ayudaMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout ayudaLayout = new javax.swing.GroupLayout(ayuda);
        ayuda.setLayout(ayudaLayout);
        ayudaLayout.setHorizontalGroup(
            ayudaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 68, Short.MAX_VALUE)
        );
        ayudaLayout.setVerticalGroup(
            ayudaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 65, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(prog, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(reserva, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(casa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(cartera, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ayuda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cartera, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(prog, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(reserva, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(casa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ayuda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setText("COMPRA");

        Cancelar.setBackground(new java.awt.Color(180, 194, 197));
        Cancelar.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        Cancelar.setForeground(new java.awt.Color(250, 250, 250));
        Cancelar.setText("Cancelar");
        Cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout graficaLayout = new javax.swing.GroupLayout(grafica);
        grafica.setLayout(graficaLayout);
        graficaLayout.setHorizontalGroup(
            graficaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 432, Short.MAX_VALUE)
        );
        graficaLayout.setVerticalGroup(
            graficaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 37, Short.MAX_VALUE)
        );

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("3. RESUMEN Y PAGO");

        jScrollPane1.setBorder(null);
        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        jPanel9.setBackground(new java.awt.Color(250, 250, 250));

        jLabel14.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        jLabel14.setText("Entradas");

        jPanel8.setBackground(new java.awt.Color(146, 165, 201));
        jPanel8.setPreferredSize(new java.awt.Dimension(430, 2));

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 447, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        fechas.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        fechas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "20/12/2023", "30/12/2022", "01/01/2023" }));
        fechas.setToolTipText("Selecciona un destino");
        fechas.setEnabled(false);

        destino.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        destino.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "CAÑON DO SIL", "CAÑON SORBA", "RIO AMAZONAS" }));
        destino.setToolTipText("Selecciona un destino");
        destino.setEnabled(false);
        destino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                destinoActionPerformed(evt);
            }
        });

        jPanel4.setBackground(new java.awt.Color(146, 165, 201));
        jPanel4.setPreferredSize(new java.awt.Dimension(430, 2));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel3.setText("Adultos");
        jLabel3.setEnabled(false);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel6.setText("Fecha:");
        jLabel6.setEnabled(false);

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel8.setText("Lugar:");
        jLabel8.setEnabled(false);

        numeroNinhos.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        numeroNinhos.setModel(new javax.swing.SpinnerNumberModel(0, 0, 40, 1));
        numeroNinhos.setEnabled(false);
        numeroNinhos.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                numeroNinhosStateChanged(evt);
            }
        });

        numeroAdultos.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        numeroAdultos.setModel(new javax.swing.SpinnerNumberModel(0, 0, 40, 1));
        numeroAdultos.setEnabled(false);
        numeroAdultos.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                numeroAdultosStateChanged(evt);
            }
        });
        numeroAdultos.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                numeroAdultosMouseMoved(evt);
            }
        });
        numeroAdultos.addMouseWheelListener(new java.awt.event.MouseWheelListener() {
            public void mouseWheelMoved(java.awt.event.MouseWheelEvent evt) {
                numeroAdultosMouseWheelMoved(evt);
            }
        });
        numeroAdultos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                numeroAdultosMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                numeroAdultosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                numeroAdultosMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                numeroAdultosMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                numeroAdultosMouseReleased(evt);
            }
        });

        precioNinos.setFont(new java.awt.Font("Segoe UI", 2, 20)); // NOI18N
        precioNinos.setText("25.0");

        precioGrupo.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        precioGrupo.setText("30.0");
        precioGrupo.setEnabled(false);

        precioAdulto.setFont(new java.awt.Font("Segoe UI", 2, 20)); // NOI18N
        precioAdulto.setText("30.5");

        jLabel19.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        jLabel19.setText("Destino");

        lugarSalida.setEditable(false);
        lugarSalida.setBackground(new java.awt.Color(250, 250, 250));
        lugarSalida.setFont(new java.awt.Font("Segoe UI Historic", 0, 20)); // NOI18N
        lugarSalida.setForeground(new java.awt.Color(153, 153, 153));
        lugarSalida.setText("Ciudad");
        lugarSalida.setToolTipText("");
        lugarSalida.setDisabledTextColor(new java.awt.Color(102, 102, 102));
        lugarSalida.setEnabled(false);
        lugarSalida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });

        jLabel26.setBackground(new java.awt.Color(250, 250, 250));
        jLabel26.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(153, 153, 153));
        jLabel26.setText("Embarque salida: ");

        jLabel27.setBackground(new java.awt.Color(250, 250, 250));
        jLabel27.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(153, 153, 153));
        jLabel27.setText("Llegada");

        jPanel12.setBackground(new java.awt.Color(201, 207, 217));
        jPanel12.setPreferredSize(new java.awt.Dimension(430, 2));

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 391, Short.MAX_VALUE)
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        jLabel4.setBackground(new java.awt.Color(250, 250, 250));
        jLabel4.setFont(new java.awt.Font("Segoe UI", 2, 20)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(153, 153, 153));
        jLabel4.setText("(Estimada)");

        horaLlegada.setEditable(false);
        horaLlegada.setBackground(new java.awt.Color(250, 250, 250));
        horaLlegada.setFont(new java.awt.Font("Segoe UI Historic", 0, 24)); // NOI18N
        horaLlegada.setForeground(new java.awt.Color(153, 153, 153));
        horaLlegada.setText("10:00");
        horaLlegada.setToolTipText("");
        horaLlegada.setDisabledTextColor(new java.awt.Color(102, 102, 102));
        horaLlegada.setEnabled(false);
        horaLlegada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                horaLlegadaActionPerformed(evt);
            }
        });

        embarque.setEditable(false);
        embarque.setBackground(new java.awt.Color(250, 250, 250));
        embarque.setFont(new java.awt.Font("Segoe UI Historic", 0, 20)); // NOI18N
        embarque.setForeground(new java.awt.Color(153, 153, 153));
        embarque.setText("Embarque");
        embarque.setToolTipText("");
        embarque.setDisabledTextColor(new java.awt.Color(102, 102, 102));
        embarque.setEnabled(false);
        embarque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                embarqueActionPerformed(evt);
            }
        });

        jLabel5.setBackground(new java.awt.Color(250, 250, 250));
        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(153, 153, 153));
        jLabel5.setText("Salida :");

        jLabel11.setBackground(new java.awt.Color(250, 250, 250));
        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(153, 153, 153));
        jLabel11.setText("Ciudad salida:");

        horaSalida.setEditable(false);
        horaSalida.setBackground(new java.awt.Color(250, 250, 250));
        horaSalida.setFont(new java.awt.Font("Segoe UI Historic", 0, 24)); // NOI18N
        horaSalida.setForeground(new java.awt.Color(153, 153, 153));
        horaSalida.setText("10:00");
        horaSalida.setToolTipText("");
        horaSalida.setDisabledTextColor(new java.awt.Color(102, 102, 102));
        horaSalida.setEnabled(false);
        horaSalida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                horaSalidaActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("SansSerif", 0, 22)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(102, 102, 102));
        jLabel7.setText("Más información");

        javax.swing.GroupLayout cont4Layout = new javax.swing.GroupLayout(cont4);
        cont4.setLayout(cont4Layout);
        cont4Layout.setHorizontalGroup(
            cont4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cont4Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(cont4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(cont4Layout.createSequentialGroup()
                        .addGroup(cont4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, cont4Layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addGroup(cont4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(cont4Layout.createSequentialGroup()
                                        .addGap(108, 108, 108)
                                        .addComponent(horaSalida, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel26))
                                .addGroup(cont4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(cont4Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(embarque))
                                    .addGroup(cont4Layout.createSequentialGroup()
                                        .addGap(39, 39, 39)
                                        .addGroup(cont4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel4)
                                            .addGroup(cont4Layout.createSequentialGroup()
                                                .addComponent(jLabel27)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(horaLlegada, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(0, 0, Short.MAX_VALUE))))
                            .addGroup(cont4Layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lugarSalida))
                            .addGroup(cont4Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, 391, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(28, 28, 28))
                    .addGroup(cont4Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        cont4Layout.setVerticalGroup(
            cont4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cont4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addGroup(cont4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(lugarSalida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(cont4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26)
                    .addComponent(embarque, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(cont4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(horaSalida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(horaLlegada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel28.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel28.setText("Niños");
        jLabel28.setEnabled(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setEnabled(false);

        total.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        total.setText("0");
        total.setEnabled(false);

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel10.setText("Total:");
        jLabel10.setEnabled(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(total)
                .addGap(41, 41, 41))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(total))
                .addContainerGap(9, Short.MAX_VALUE))
        );

        jLabel29.setFont(new java.awt.Font("Segoe UI", 2, 20)); // NOI18N
        jLabel29.setText("El precio para los grupos es de: ");

        jLabel20.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        jLabel20.setText("Información de pago");

        jPanel5.setBackground(new java.awt.Color(146, 165, 201));
        jPanel5.setPreferredSize(new java.awt.Dimension(430, 2));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 440, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        jPanel3.setEnabled(false);

        CVC.setEditable(false);
        CVC.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        CVC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CVCActionPerformed(evt);
            }
        });

        jLabel23.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel23.setText("CVC:");
        jLabel23.setEnabled(false);

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel9.setText("Fecha de Caducidad:");
        jLabel9.setEnabled(false);

        jLabel12.setText("TARJETA");
        jLabel12.setEnabled(false);

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(jLabel12)
                .addContainerGap(57, Short.MAX_VALUE))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addComponent(jLabel12)
                .addGap(17, 17, 17))
        );

        fechaCaducidad.setEditable(false);
        fechaCaducidad.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        fechaCaducidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fechaCaducidadActionPerformed(evt);
            }
        });

        nombre.setEditable(false);
        nombre.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel13.setText("Método de pago:");
        jLabel13.setEnabled(false);

        nTarjeta.setEditable(false);
        nTarjeta.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        nTarjeta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nTarjetaActionPerformed(evt);
            }
        });

        jLabel21.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel21.setText("Nombre titular:");
        jLabel21.setEnabled(false);

        jLabel24.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel24.setText("Número tarjeta:");
        jLabel24.setEnabled(false);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel24)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel21)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(nombre, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                    .addComponent(nTarjeta))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(134, 134, 134)
                                .addComponent(jLabel23)
                                .addGap(18, 18, 18)
                                .addComponent(CVC, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(fechaCaducidad, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(68, 68, 68))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabel13)
                        .addGap(31, 31, 31))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nTarjeta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel24))
                .addGap(44, 44, 44)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fechaCaducidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(44, 44, 44)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CVC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel23))
                .addGap(0, 20, Short.MAX_VALUE))
        );

        btnPago.setBackground(new java.awt.Color(250, 250, 250));
        btnPago.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        btnPago.setText("Modificar");
        btnPago.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPagoActionPerformed(evt);
            }
        });

        btnEntradas.setBackground(new java.awt.Color(250, 250, 250));
        btnEntradas.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        btnEntradas.setText("Modificar");
        btnEntradas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEntradasActionPerformed(evt);
            }
        });

        btnEntradas1.setBackground(new java.awt.Color(250, 250, 250));
        btnEntradas1.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        btnEntradas1.setText("Modificar");
        btnEntradas1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEntradas1ActionPerformed(evt);
            }
        });

        text5.setFont(new java.awt.Font("Segoe UI", 2, 20)); // NOI18N
        text5.setText("€/persona");

        text6.setFont(new java.awt.Font("Segoe UI", 2, 20)); // NOI18N
        text6.setText("€/persona");

        text7.setFont(new java.awt.Font("Segoe UI", 2, 20)); // NOI18N
        text7.setText("€/persona");

        text8.setFont(new java.awt.Font("Segoe UI", 2, 20)); // NOI18N
        text8.setText("€/persona");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(138, 138, 138))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 473, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(42, Short.MAX_VALUE))))
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jLabel6))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel9Layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel28))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel9Layout.createSequentialGroup()
                                        .addComponent(precioAdulto)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(text7)
                                        .addGap(85, 85, 85)
                                        .addComponent(numeroAdultos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel9Layout.createSequentialGroup()
                                        .addComponent(precioNinos)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(text8)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(numeroNinhos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, 447, Short.MAX_VALUE)
                            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 447, Short.MAX_VALUE)
                            .addGroup(jPanel9Layout.createSequentialGroup()
                                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel14))
                                .addGap(106, 106, 106)
                                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel9Layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(btnEntradas))
                                    .addComponent(fechas, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(destino, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jLabel20)
                        .addGap(18, 18, 18)
                        .addComponent(btnPago))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(cont4, javax.swing.GroupLayout.PREFERRED_SIZE, 473, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                        .addComponent(jLabel29)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(precioGrupo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(text6)
                        .addGap(72, 72, 72))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                        .addComponent(btnEntradas1)
                        .addGap(149, 149, 149))))
            .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel9Layout.createSequentialGroup()
                    .addGap(38, 38, 38)
                    .addComponent(jLabel19)
                    .addContainerGap(402, Short.MAX_VALUE)))
            .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel9Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(text5)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addComponent(btnEntradas1)
                .addGap(3, 3, 3)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(destino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(18, 18, 18)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fechas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(btnEntradas))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(numeroAdultos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(precioAdulto)
                    .addComponent(text7))
                .addGap(18, 18, 18)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(numeroNinhos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(precioNinos)
                    .addComponent(text8)
                    .addComponent(jLabel28))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(precioGrupo)
                    .addComponent(text6)
                    .addComponent(jLabel29))
                .addGap(24, 24, 24)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cont4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(btnPago))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(8, Short.MAX_VALUE))
            .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel9Layout.createSequentialGroup()
                    .addGap(10, 10, 10)
                    .addComponent(jLabel19)
                    .addContainerGap(1168, Short.MAX_VALUE)))
            .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel9Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(text5)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jScrollPane1.setViewportView(jPanel9);

        siguiente.setBackground(new java.awt.Color(95, 164, 171));
        siguiente.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        siguiente.setForeground(new java.awt.Color(255, 255, 255));
        siguiente.setText("Finalizar");
        siguiente.setEnabled(false);
        siguiente.setFocusPainted(false);
        siguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                siguienteActionPerformed(evt);
            }
        });

        anterior.setBackground(new java.awt.Color(164, 185, 187));
        anterior.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        anterior.setForeground(new java.awt.Color(250, 250, 250));
        anterior.setText("Anterior");
        anterior.setFocusPainted(false);
        anterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                anteriorActionPerformed(evt);
            }
        });

        volver.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                volverMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout volverLayout = new javax.swing.GroupLayout(volver);
        volver.setLayout(volverLayout);
        volverLayout.setHorizontalGroup(
            volverLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 52, Short.MAX_VALUE)
        );
        volverLayout.setVerticalGroup(
            volverLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 378, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(logo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addComponent(volver, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(45, 45, 45))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(64, 64, 64)
                                .addComponent(grafica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(17, 17, 17))))
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 506, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(anterior, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(siguiente, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(logo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Cancelar)
                            .addComponent(jLabel2)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(volver, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(grafica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 492, Short.MAX_VALUE)
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(anterior, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(siguiente, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void carteraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_carteraMouseClicked
        // TODO add your handling code here:
        Cartera pp = new Cartera();

        pp.setV(this.v);
        v.setContentPane(pp);
        v.setVisible(true);
        pp.setVisible(true);
        pp.cargarImagenes();
    }//GEN-LAST:event_carteraMouseClicked

    private void reservaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reservaMouseClicked
          // TODO add your handling code here:
    }//GEN-LAST:event_reservaMouseClicked

    private void progMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_progMouseClicked
        Viajes pp = new Viajes();

        pp.setV(this.v);
        v.setContentPane(pp);
        v.setVisible(true);
        pp.setVisible(true);
        pp.cargarImagenes();
    }//GEN-LAST:event_progMouseClicked

    private void ayudaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ayudaMouseClicked
        // TODO add your handling code here:
        Ayuda pp = new Ayuda();

        pp.setV(this.v);
        v.setContentPane(pp);
        v.setVisible(true);
        pp.setVisible(true);
        pp.cargarImagenes();
    }//GEN-LAST:event_ayudaMouseClicked

    private void casaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_casaMouseClicked
        // TODO add your handling code here:
        // TODO add your handling code here:
        Inicial pp = new Inicial();

        pp.setV(this.v);
        v.setContentPane(pp);
        v.setVisible(true);
        pp.setVisible(true);
        pp.cargarImagenes();
    }//GEN-LAST:event_casaMouseClicked

    private void destinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_destinoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_destinoActionPerformed

    private void siguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_siguienteActionPerformed


     // TODO add your handling code here:
        // TODO add your handling code here:
        ResumenPago pp = new ResumenPago(a, pago);
        pp.setV(this.v);
        v.setContentPane(pp);
        v.setVisible(true);
        pp.setVisible(true);
        pp.cargarImagenes();




        // TODO add your handling code here:
        // TODO add your handling code here:
        //   float numero_entradas_adulto, float numero_entradas_nino, String destino, String fecha, String lugar_salida, String embarcadero, String hora_salida, String hora_llegada) {
       
    }//GEN-LAST:event_siguienteActionPerformed

    private void horaSalidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_horaSalidaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_horaSalidaActionPerformed

    private void embarqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_embarqueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_embarqueActionPerformed

    private void horaLlegadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_horaLlegadaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_horaLlegadaActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void numeroAdultosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_numeroAdultosMouseClicked

    }//GEN-LAST:event_numeroAdultosMouseClicked

    private void numeroAdultosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_numeroAdultosMouseEntered

    }//GEN-LAST:event_numeroAdultosMouseEntered

    private void numeroAdultosMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_numeroAdultosMouseMoved

    }//GEN-LAST:event_numeroAdultosMouseMoved

    private void numeroAdultosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_numeroAdultosMouseExited

    }//GEN-LAST:event_numeroAdultosMouseExited

    private void numeroAdultosMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_numeroAdultosMousePressed

    }//GEN-LAST:event_numeroAdultosMousePressed

    private void numeroAdultosMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_numeroAdultosMouseReleased
        // TODO add your handling code here:
   
    }//GEN-LAST:event_numeroAdultosMouseReleased

    private void numeroAdultosMouseWheelMoved(java.awt.event.MouseWheelEvent evt) {//GEN-FIRST:event_numeroAdultosMouseWheelMoved

    }//GEN-LAST:event_numeroAdultosMouseWheelMoved

    private void numeroAdultosStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_numeroAdultosStateChanged
        // TODO add your handling code here:
             // TODO add your handling code here:
             // TODO add your handling code here:
                // TODO add your handling code here:
        int numeroAdultos = (int) this.numeroAdultos.getValue();
        int numeroNinos = (int) this.numeroNinhos.getValue();
        if (numeroAdultos + numeroNinos >= 6) {
            this.total.setText(String.valueOf((numeroAdultos + numeroNinos) * Float.parseFloat(this.precioGrupo.getText())));
        } else {

            this.total.setText(String.valueOf(numeroAdultos * Float.parseFloat(this.precioAdulto.getText()) + numeroNinos * Float.parseFloat(this.precioNinos.getText())));
        }
    }//GEN-LAST:event_numeroAdultosStateChanged

    private void numeroNinhosStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_numeroNinhosStateChanged
        // TODO add your handling code here:
             // TODO add your handling code here:
             // TODO add your handling code here:
                // TODO add your handling code here:
        int numeroAdultos = (int) this.numeroAdultos.getValue();
        int numeroNinos = (int) this.numeroNinhos.getValue();
        if (numeroAdultos + numeroNinos > 6) {
            this.total.setText(String.valueOf((numeroAdultos + numeroNinos) * Float.parseFloat(this.precioGrupo.getText())));
        } else {

            this.total.setText(String.valueOf(numeroAdultos * Float.parseFloat(this.precioAdulto.getText()) + numeroNinos * Float.parseFloat(this.precioNinos.getText())));
        }
    }//GEN-LAST:event_numeroNinhosStateChanged

    private void anteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_anteriorActionPerformed
        // TODO add your handling code here:
        // TODO add your handling code here:
        // TODO add your handling code here:
        Reserva2 pp = new Reserva2(this.a,pago );

        pp.setV(this.v);
        v.setContentPane(pp);
        v.setVisible(true);
        pp.setVisible(true);
        pp.cargarImagenes();
    }//GEN-LAST:event_anteriorActionPerformed

    private void volverMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_volverMouseClicked
        // TODO add your handling code here:
        // TODO add your handling code here:
        Reserva2 pp = new Reserva2(this.a,  this.pago);

        pp.setV(this.v);
        v.setContentPane(pp);
        v.setVisible(true);
        pp.setVisible(true);
        pp.cargarImagenes();

    }//GEN-LAST:event_volverMouseClicked

    private void nTarjetaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nTarjetaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nTarjetaActionPerformed

    private void nombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreActionPerformed

    private void fechaCaducidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fechaCaducidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fechaCaducidadActionPerformed

    private void CVCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CVCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CVCActionPerformed

    private void btnEntradasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEntradasActionPerformed
        // TODO add your handling code here:
        
                // TODO add your handling code here:
        // TODO add your handling code here:
        Reserva pp = new Reserva(this.a,true,  this.pago);

        pp.setV(this.v);
        v.setContentPane(pp);
        v.setVisible(true);
        pp.setVisible(true);
        pp.cargarImagenes();
        
        
        
        
    }//GEN-LAST:event_btnEntradasActionPerformed

    private void btnPagoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPagoActionPerformed
                // TODO add your handling code here:
        // TODO add your handling code here:
        Reserva2 pp = new Reserva2(this.a,  this.pago);

        pp.setV(this.v);
        v.setContentPane(pp);
        v.setVisible(true);
        pp.setVisible(true);
        pp.cargarImagenes();
                // TODO add your handling code here:
    }//GEN-LAST:event_btnPagoActionPerformed

    private void btnEntradas1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEntradas1ActionPerformed
        // TODO add your handling code here:
                // TODO add your handling code here:
        
                // TODO add your handling code here:
        // TODO add your handling code here:
        Reserva pp = new Reserva(this.a,true,  this.pago);

        pp.setV(this.v);
        v.setContentPane(pp);
        v.setVisible(true);
        pp.setVisible(true);
        pp.cargarImagenes();
        
    }//GEN-LAST:event_btnEntradas1ActionPerformed

    private void CancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelarActionPerformed
 Dialogo a= new Dialogo(v, true, v);
          
           a.setAlwaysOnTop(true);
           a.setLocationRelativeTo(v); a.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_CancelarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CVC;
    private javax.swing.JButton Cancelar;
    private javax.swing.JButton anterior;
    private javax.swing.JPanel ayuda;
    private javax.swing.JButton btnEntradas;
    private javax.swing.JButton btnEntradas1;
    private javax.swing.JButton btnPago;
    private javax.swing.JPanel buscar;
    private javax.swing.JPanel cartera;
    private javax.swing.JPanel casa;
    private javax.swing.JPanel cont4;
    private javax.swing.JComboBox<String> destino;
    private javax.swing.JTextField embarque;
    private javax.swing.JTextField fechaCaducidad;
    private javax.swing.JComboBox<String> fechas;
    private javax.swing.JPanel grafica;
    private javax.swing.JTextField horaLlegada;
    private javax.swing.JTextField horaSalida;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jbusqueda3;
    private javax.swing.JPanel logo;
    private javax.swing.JTextField lugarSalida;
    private javax.swing.JTextField nTarjeta;
    private javax.swing.JTextField nombre;
    private javax.swing.JSpinner numeroAdultos;
    private javax.swing.JSpinner numeroNinhos;
    private javax.swing.JLabel precioAdulto;
    private javax.swing.JLabel precioGrupo;
    private javax.swing.JLabel precioNinos;
    private javax.swing.JPanel prog;
    private javax.swing.JPanel reserva;
    private javax.swing.JButton siguiente;
    private javax.swing.JLabel text5;
    private javax.swing.JLabel text6;
    private javax.swing.JLabel text7;
    private javax.swing.JLabel text8;
    private javax.swing.JLabel total;
    private javax.swing.JPanel volver;
    // End of variables declaration//GEN-END:variables
}
