/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package prueba1;

import clase.Imagen;
import clase.RoundedBorder;
import clase.TextPrompt;

import java.awt.Color;
import java.util.ArrayList;

/**
 *
 * @author nerea
 */
public class ViajesMasInfo extends javax.swing.JPanel {

    private ventana v;
    private String foto;
    /**
     * Creates new form Viajes
     */
    public ViajesMasInfo(String rutafoto,String destino, String fecha, String embarcadero, Float precio_Adulto, Float precio_Grupo, Float precio_Niño, String Descripcion, String duracion, String hora_salida, String lugar_salida) {
        initComponents();
        this.destino.setText(destino.toUpperCase());
        this.duracion.setText(duracion);
        this.localidad.setText(lugar_salida);
        this.lugarsalida.setText(lugar_salida);
        this.lugarsalida1.setText(embarcadero);
        this.precioAdulto.setText(precio_Adulto.toString());
        this.precioNiño.setText(precio_Niño.toString());
        this.precioGrupo.setText(precio_Grupo.toString());
        this.horaSalida1.setText(hora_salida);
        this.descripcion.setText(Descripcion);
        this.foto= rutafoto;
        
        
   
    }

    public ventana getV() {
        return v;
    }

    public void setV(ventana v) {
        this.v = v;
    }

    public void cargarImagenes() {
        Imagen a = new Imagen(casa, "/Images/casa.png");
        casa.add(a).repaint();

        a = new Imagen(prog, "/Images/progseleccion.png");
        prog.add(a).repaint();

        a = new Imagen(reserva, "/Images/reserva.png");
        reserva.add(a).repaint();
        a = new Imagen(ayuda, "/Images/ayuda.png");
        ayuda.add(a).repaint();
        a = new Imagen(cartera, "/Images/cartera.png");
        cartera.add(a).repaint();
        a = new Imagen(buscar, "/Images/buscar.png");
        buscar.add(a).repaint();

        a = new Imagen(logo, "/Images/logo.png");
        logo.add(a).repaint();
        a = new Imagen(destino0, foto);
        destino0.add(a).repaint();
        a = new Imagen(volver, "/Images/volver.png");
        volver.add(a).repaint();
        a = new Imagen(maps0, "/Images/maps0.png");
        maps0.add(a).repaint();
        a = new Imagen(discapacidad, "/Images/discapacidad.png");
        discapacidad.add(a).repaint();
        datosinteres.setBackground(new Color(0, 0, 0, 0));
        jScrollPane3.setBackground(new Color(0, 0, 0, 0));
        a = new Imagen(discapacidad1, "/Images/dicapacidad1.png");
        discapacidad1.add(a).repaint();
        a = new Imagen(comida, "/Images/comida.png");
        comida.add(a).repaint();
        
        RoundedBorder b= new RoundedBorder(8);
        btnreserva.setBorder(b);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        logo = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jbusqueda3 = new javax.swing.JTextField();
        buscar = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        cartera = new javax.swing.JPanel();
        casa = new javax.swing.JPanel();
        reserva = new javax.swing.JPanel();
        prog = new javax.swing.JPanel();
        ayuda = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        destino0 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        duracion = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        localidad = new javax.swing.JLabel();
        precioAdulto = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        precioGrupo = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jPanel4 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        precioNiño = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        horaSalida1 = new javax.swing.JLabel();
        lugarsalida = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        maps0 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        lugarsalida1 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        datosinteres = new javax.swing.JTextArea();
        jPanel9 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        descripcion = new javax.swing.JTextArea();
        discapacidad = new javax.swing.JPanel();
        discapacidad1 = new javax.swing.JPanel();
        comida = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        volver = new javax.swing.JPanel();
        destino = new javax.swing.JLabel();
        btnreserva = new javax.swing.JButton();

        setBackground(new java.awt.Color(250, 250, 250));
        setPreferredSize(new java.awt.Dimension(521, 946));

        javax.swing.GroupLayout logoLayout = new javax.swing.GroupLayout(logo);
        logo.setLayout(logoLayout);
        logoLayout.setHorizontalGroup(
            logoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 135, Short.MAX_VALUE)
        );
        logoLayout.setVerticalGroup(
            logoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 48, Short.MAX_VALUE)
        );

        jPanel6.setBackground(new java.awt.Color(146, 194, 197));

        jbusqueda3.setBackground(new java.awt.Color(146, 194, 197));
        jbusqueda3.setFont(new java.awt.Font("Segoe UI", 1, 21)); // NOI18N
        jbusqueda3.setForeground(new java.awt.Color(255, 255, 255));
        jbusqueda3.setBorder(null);
        jbusqueda3.setCaretColor(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout buscarLayout = new javax.swing.GroupLayout(buscar);
        buscar.setLayout(buscarLayout);
        buscarLayout.setHorizontalGroup(
            buscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 52, Short.MAX_VALUE)
        );
        buscarLayout.setVerticalGroup(
            buscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 45, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addComponent(jbusqueda3, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(buscar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbusqueda3, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(146, 194, 197));

        cartera.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cartera.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                carteraMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout carteraLayout = new javax.swing.GroupLayout(cartera);
        cartera.setLayout(carteraLayout);
        carteraLayout.setHorizontalGroup(
            carteraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 68, Short.MAX_VALUE)
        );
        carteraLayout.setVerticalGroup(
            carteraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 65, Short.MAX_VALUE)
        );

        casa.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        casa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                casaMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout casaLayout = new javax.swing.GroupLayout(casa);
        casa.setLayout(casaLayout);
        casaLayout.setHorizontalGroup(
            casaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 68, Short.MAX_VALUE)
        );
        casaLayout.setVerticalGroup(
            casaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 65, Short.MAX_VALUE)
        );

        reserva.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        reserva.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                reservaMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout reservaLayout = new javax.swing.GroupLayout(reserva);
        reserva.setLayout(reservaLayout);
        reservaLayout.setHorizontalGroup(
            reservaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 68, Short.MAX_VALUE)
        );
        reservaLayout.setVerticalGroup(
            reservaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 65, Short.MAX_VALUE)
        );

        prog.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        prog.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                progMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout progLayout = new javax.swing.GroupLayout(prog);
        prog.setLayout(progLayout);
        progLayout.setHorizontalGroup(
            progLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 68, Short.MAX_VALUE)
        );
        progLayout.setVerticalGroup(
            progLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 65, Short.MAX_VALUE)
        );

        ayuda.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ayuda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ayudaMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout ayudaLayout = new javax.swing.GroupLayout(ayuda);
        ayuda.setLayout(ayudaLayout);
        ayudaLayout.setHorizontalGroup(
            ayudaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 68, Short.MAX_VALUE)
        );
        ayudaLayout.setVerticalGroup(
            ayudaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 65, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(prog, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(reserva, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(casa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(cartera, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ayuda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cartera, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(prog, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(reserva, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(casa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ayuda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setText("VIAJES > ");

        jScrollPane1.setBorder(null);

        jPanel1.setBackground(new java.awt.Color(250, 250, 250));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        destino0.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        destino0.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout destino0Layout = new javax.swing.GroupLayout(destino0);
        destino0.setLayout(destino0Layout);
        destino0Layout.setHorizontalGroup(
            destino0Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 380, Short.MAX_VALUE)
        );
        destino0Layout.setVerticalGroup(
            destino0Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 253, Short.MAX_VALUE)
        );

        jPanel1.add(destino0, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 21)); // NOI18N
        jLabel4.setText("Duración");

        duracion.setFont(new java.awt.Font("Segoe UI", 1, 21)); // NOI18N
        duracion.setText("2h");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jLabel4))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(duracion)))
                .addContainerGap(44, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(duracion)
                .addGap(12, 12, 12))
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 270, 150, 80));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 21)); // NOI18N
        jLabel3.setText("Lugar de salida");

        localidad.setFont(new java.awt.Font("Segoe UI", 1, 21)); // NOI18N
        localidad.setText("Monforte de Lemos");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(jLabel3))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(localidad)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(localidad)
                .addGap(0, 16, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 270, 220, 80));

        precioAdulto.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        precioAdulto.setText("10.0");
        jPanel1.add(precioAdulto, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 430, -1, -1));

        jLabel7.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        jLabel7.setText("Precios");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 370, -1, -1));

        precioGrupo.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        precioGrupo.setText("10.0");
        jPanel1.add(precioGrupo, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 470, -1, -1));

        jLabel8.setFont(new java.awt.Font("SansSerif", 0, 20)); // NOI18N
        jLabel8.setText("(6 o más):");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 470, -1, 30));

        jScrollPane2.setBorder(null);
        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane2.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Segoe UI", 2, 16)); // NOI18N
        jTextArea1.setLineWrap(true);
        jTextArea1.setRows(5);
        jTextArea1.setText("* Si el número de entradas totales (niños+adultos) es 6 o más, se aplicará de forma directa el precio de grupo, no será válido el precio niño");
        jTextArea1.setWrapStyleWord(true);
        jTextArea1.setBorder(null);
        jScrollPane2.setViewportView(jTextArea1);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 510, 420, 70));

        jPanel4.setBackground(new java.awt.Color(146, 165, 201));
        jPanel4.setPreferredSize(new java.awt.Dimension(430, 2));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 420, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 400, 420, 10));

        jLabel9.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        jLabel9.setText("Niños:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 430, -1, -1));

        jLabel11.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        jLabel11.setText("Precio grupos ");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 470, -1, -1));

        precioNiño.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        precioNiño.setText("10.0");
        jPanel1.add(precioNiño, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 430, -1, -1));

        jPanel7.setBackground(new java.awt.Color(146, 165, 201));
        jPanel7.setPreferredSize(new java.awt.Dimension(430, 2));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 430, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 620, 430, 10));

        jLabel10.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        jLabel10.setText("Salida");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 590, -1, -1));

        jLabel12.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        jLabel12.setText("Adultos: ");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 430, -1, -1));

        jLabel14.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        jLabel14.setText("Fechas disponibles:");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 760, -1, -1));

        horaSalida1.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        horaSalida1.setText("12:99 h");
        jPanel1.add(horaSalida1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 640, -1, -1));

        lugarsalida.setFont(new java.awt.Font("Segoe UI", 1, 21)); // NOI18N
        lugarsalida.setText("Castro caldelas");
        jPanel1.add(lugarsalida, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 680, -1, -1));

        jLabel15.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        jLabel15.setText("Embarcadero:");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 720, -1, -1));

        javax.swing.GroupLayout maps0Layout = new javax.swing.GroupLayout(maps0);
        maps0.setLayout(maps0Layout);
        maps0Layout.setHorizontalGroup(
            maps0Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 310, Short.MAX_VALUE)
        );
        maps0Layout.setVerticalGroup(
            maps0Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 150, Short.MAX_VALUE)
        );

        jPanel1.add(maps0, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 850, 310, 150));

        jLabel16.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        jLabel16.setText("Localidad de salida:");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 680, -1, -1));

        lugarsalida1.setFont(new java.awt.Font("Segoe UI", 1, 21)); // NOI18N
        lugarsalida1.setText("\tEmbarcadero de Abeleda");
        jPanel1.add(lugarsalida1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 720, -1, -1));

        jPanel8.setBackground(new java.awt.Color(146, 165, 201));
        jPanel8.setPreferredSize(new java.awt.Dimension(430, 2));

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 430, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 1040, 430, 10));

        jLabel13.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        jLabel13.setText("Descripcion");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 1010, -1, -1));

        jScrollPane3.setBorder(null);

        datosinteres.setEditable(false);
        datosinteres.setBackground(new java.awt.Color(250, 250, 250));
        datosinteres.setColumns(20);
        datosinteres.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        datosinteres.setLineWrap(true);
        datosinteres.setRows(5);
        datosinteres.setText("- Todos nuestros barcos cuentan con acceso para personas con discapacidades físicas.\n\n- Tenemos a vuestra disposición tecnologías para poder conectarse a sonotones para aquellas personas que lo precisen.\n\n- En el interior del barco existe una zona de cafetería en la que se pueden comprar tanto bebida como bocadillos");
        datosinteres.setWrapStyleWord(true);
        datosinteres.setBorder(null);
        jScrollPane3.setViewportView(datosinteres);

        jPanel1.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 1320, 390, 430));

        jPanel9.setBackground(new java.awt.Color(146, 165, 201));
        jPanel9.setPreferredSize(new java.awt.Dimension(430, 2));

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 430, Short.MAX_VALUE)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 1300, 430, 10));

        jLabel17.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        jLabel17.setText("Datos de interés");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 1270, -1, -1));

        jScrollPane4.setBorder(null);

        descripcion.setEditable(false);
        descripcion.setColumns(20);
        descripcion.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        descripcion.setLineWrap(true);
        descripcion.setRows(5);
        descripcion.setWrapStyleWord(true);
        jScrollPane4.setViewportView(descripcion);

        jPanel1.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 1070, 430, 190));

        javax.swing.GroupLayout discapacidadLayout = new javax.swing.GroupLayout(discapacidad);
        discapacidad.setLayout(discapacidadLayout);
        discapacidadLayout.setHorizontalGroup(
            discapacidadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );
        discapacidadLayout.setVerticalGroup(
            discapacidadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        jPanel1.add(discapacidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 1320, 40, 40));

        javax.swing.GroupLayout discapacidad1Layout = new javax.swing.GroupLayout(discapacidad1);
        discapacidad1.setLayout(discapacidad1Layout);
        discapacidad1Layout.setHorizontalGroup(
            discapacidad1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );
        discapacidad1Layout.setVerticalGroup(
            discapacidad1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        jPanel1.add(discapacidad1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 1440, -1, -1));

        javax.swing.GroupLayout comidaLayout = new javax.swing.GroupLayout(comida);
        comida.setLayout(comidaLayout);
        comidaLayout.setHorizontalGroup(
            comidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );
        comidaLayout.setVerticalGroup(
            comidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        jPanel1.add(comida, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 1610, -1, -1));

        jLabel18.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        jLabel18.setText("Hora de salida:");
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 640, -1, -1));

        jComboBox1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "20/12/2022", "30/12/2022", "01/01/2023" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 760, 180, 40));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel5.setText("€");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 470, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel6.setText("€");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 430, -1, -1));

        jLabel19.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel19.setText("€");
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 430, -1, -1));

        jScrollPane1.setViewportView(jPanel1);

        volver.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        volver.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                volverMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout volverLayout = new javax.swing.GroupLayout(volver);
        volver.setLayout(volverLayout);
        volverLayout.setHorizontalGroup(
            volverLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 57, Short.MAX_VALUE)
        );
        volverLayout.setVerticalGroup(
            volverLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        destino.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        destino.setText("jLabel1");

        btnreserva.setBackground(new java.awt.Color(146, 194, 197));
        btnreserva.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnreserva.setForeground(new java.awt.Color(250, 250, 250));
        btnreserva.setText("RESERVA YA!");
        btnreserva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnreservaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1))
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(volver, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(destino)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(logo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(17, 17, 17))))
            .addGroup(layout.createSequentialGroup()
                .addGap(132, 132, 132)
                .addComponent(btnreserva, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(logo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(61, 61, 61)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(destino))
                            .addComponent(volver, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(28, 28, 28))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(btnreserva, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 557, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void carteraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_carteraMouseClicked
        // TODO add your handling code here:
        Cartera pp = new Cartera();

        pp.setV(this.v);
        v.setContentPane(pp);
        v.setVisible(true);
        pp.setVisible(true);
        pp.cargarImagenes();
    }//GEN-LAST:event_carteraMouseClicked

    private void reservaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reservaMouseClicked
        Reserva pp = new Reserva();

        pp.setV(this.v);
        v.setContentPane(pp);
        v.setVisible(true);
        pp.setVisible(true);
        pp.cargarImagenes();        // TODO add your handling code here:
    }//GEN-LAST:event_reservaMouseClicked

    private void progMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_progMouseClicked
        Viajes pp = new Viajes();

        pp.setV(this.v);
        v.setContentPane(pp);
        v.setVisible(true);
        pp.setVisible(true);
        pp.cargarImagenes();
    }//GEN-LAST:event_progMouseClicked

    private void ayudaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ayudaMouseClicked
        // TODO add your handling code here:
        Ayuda pp = new Ayuda();

        pp.setV(this.v);
        v.setContentPane(pp);
        v.setVisible(true);
        pp.setVisible(true);
        pp.cargarImagenes();
    }//GEN-LAST:event_ayudaMouseClicked

    private void casaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_casaMouseClicked
        // TODO add your handling code here:
        // TODO add your handling code here:
        Inicial pp = new Inicial();

        pp.setV(this.v);
        v.setContentPane(pp);
        v.setVisible(true);
        pp.setVisible(true);
        pp.cargarImagenes();
    }//GEN-LAST:event_casaMouseClicked

    private void volverMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_volverMouseClicked
        // TODO add your handling code here:
        Viajes pp = new Viajes();

        pp.setV(this.v);
        v.setContentPane(pp);
        v.setVisible(true);
        pp.setVisible(true);
        pp.cargarImagenes();

    }//GEN-LAST:event_volverMouseClicked

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void btnreservaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnreservaActionPerformed
        // TODO add your handling code here:
        clase.Reserva res=new clase.Reserva(Float.parseFloat(this.precioAdulto.getText()), Float.parseFloat(this.precioNiño.getText()), 
                Float.parseFloat(this.precioGrupo.getText()), (int) 0, (int)0,(int)0, 
                this.destino.getText(), this.jComboBox1.getSelectedItem().toString(), this.lugarsalida.getText(), this.lugarsalida1.getText(),
                this.horaSalida1.getText(), "12:00");
        ArrayList<String>  auxiliar=new ArrayList<>();
        for(int i =0; i<=this.jComboBox1.getMaximumRowCount();i++){
            auxiliar.add(this.jComboBox1.getItemAt(i));
        }
        res.setPosibles_fechas(auxiliar);
                // TODO add your handling code here:
        Reserva pp = new Reserva(res, false);
        System.out.println(this.destino.getText());
        pp.setV(this.v);
        v.setContentPane(pp);
        v.setVisible(true);
        pp.setVisible(true);
        pp.cargarImagenes();

        
    }//GEN-LAST:event_btnreservaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ayuda;
    private javax.swing.JButton btnreserva;
    private javax.swing.JPanel buscar;
    private javax.swing.JPanel cartera;
    private javax.swing.JPanel casa;
    private javax.swing.JPanel comida;
    private javax.swing.JTextArea datosinteres;
    private javax.swing.JTextArea descripcion;
    private javax.swing.JLabel destino;
    private javax.swing.JPanel destino0;
    private javax.swing.JPanel discapacidad;
    private javax.swing.JPanel discapacidad1;
    private javax.swing.JLabel duracion;
    private javax.swing.JLabel horaSalida1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jbusqueda3;
    private javax.swing.JLabel localidad;
    private javax.swing.JPanel logo;
    private javax.swing.JLabel lugarsalida;
    private javax.swing.JLabel lugarsalida1;
    private javax.swing.JPanel maps0;
    private javax.swing.JLabel precioAdulto;
    private javax.swing.JLabel precioGrupo;
    private javax.swing.JLabel precioNiño;
    private javax.swing.JPanel prog;
    private javax.swing.JPanel reserva;
    private javax.swing.JPanel volver;
    // End of variables declaration//GEN-END:variables
}
